# Generated by Django 5.0.2 on 2024-11-12 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('genero', models.CharField(max_length=50, verbose_name='Género')),
                ('clasificacion', models.CharField(max_length=10, verbose_name='Clasificación')),
                ('duracion', models.PositiveIntegerField(verbose_name='Duración (min)')),
                ('sinopsis', models.TextField(blank=True, null=True, verbose_name='Sinopsis')),
                ('fecha_estreno', models.DateField(blank=True, null=True, verbose_name='Fecha de Estreno')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_peliculas/', verbose_name='Imagen de la Película')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numero_sala', models.CharField(max_length=5)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('sala', models.CharField(max_length=10, verbose_name='Sala')),
                ('id_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='cartelera.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id_boleto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('asiento', models.CharField(max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.cliente')),
                ('id_proyeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.proyeccion')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.venta')),
            ],
        ),
    ]
