# Generated by Django 5.0.2 on 2024-11-11 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.cliente'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='id_proyeccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.proyeccion'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.venta'),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='id_pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.pelicula'),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='id_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.sala'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.empleado'),
        ),
    ]
